[project]
name = "Simple-Python-Proxy"
version = "0.1.0"
description = "A simple proxy mad with python libraries"
authors = ["Soxregretslife"]
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "flask>=3.1.0",
    "requests>=2.32.3",
]
